# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "2024-app"
client_id = "c8bcacccd9d5f4a7c3122a8d3b5d118e"
application_url = "https://en-stockholm-festivals-av.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://en-stockholm-festivals-av.trycloudflare.com/auth/callback",
  "https://en-stockholm-festivals-av.trycloudflare.com/auth/shopify/callback",
  "https://en-stockholm-festivals-av.trycloudflare.com/api/auth/callback",
  "https://en-stockholm-festivals-av.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "oroa-development.myshopify.com"
